version: '2.0'
services:
  web:
    build: ./config/nginx
    image: nginx
    ports:
      - '80'
    links:
      - app
  app:
    build: .
    image: ror
    links:
      - db
  db:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root